apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prospecat-com-tls
spec:
  secretName: prospecat-com
  issuerRef:
    name: letsencrypt-prod
  commonName: www.prospecat.com
  dnsNames:
    - www.prospecat.com
